### ISSUE TITLE
Add CI for pushes, PRs, and periodic CI

### ISSUE THREAD

**Issue by hungrybluedev** [hungrybluedev/xlsx#2]
1. Will help vet contributor contributions.
2. Ensure projects compiles with latest V.

**Comment by spytheman** [comment]
Some of it was done in #3 .

**Comment by spytheman** [comment]
There are no periodic runs though for now 🤔 .

**Comment by hungrybluedev** [comment]
Added periodic run in https://github.com/hungrybluedev/xlsx/commit/2b7f4f2799571af4f13a3529dd905792d2ab44a8
